// Localhost
get http://localhost:8080/contacts
###
get http://localhost:8080/contacts/6378191bd909416a9798b4e7

###
get http://localhost:8080/contacts/6378191bd909416a9798b4e8
###
get http://localhost:8080/contacts/6378191bd909416a9798b4e9

###
post http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "Name": "Rebecca",
  "Surname": "Mushayawaro",
  "Email": "rebeccan@gmail.com",
  "FavoriteColor": "Red",
  "Birthday": "06/04/82"
}
###
put http://localhost:8080/contacts/6378191bd909416a9798b4e9HTTP/1.1
content-type: application/json

{
  "Name": "Cecil",
  "Surname": "Mushayawaro",
  "Email": "ccan@gmail.com",
  "FavoriteColor": "Red",
  "Birthday": "06/04/82"
}
###
delete http://localhost:8080/contacts/6378191bd909416a9798b4e9 HTTP/1.1

// render

###
get https://mabundur341.onrender.com/contacts HTTP/1.1

###
get https://mabundur341.onrender.com/contacts/6378191bd909416a9798b4e7 HTTP/1.1

###
get https://mabundur341.onrender.com/contacts/6378191bd909416a9798b4e8 HTTP/1.1
###
get https://mabundur341.onrender.com/contacts/6378191bd909416a9798b4e9 HTTP/1.1

###
post https://mabundur341.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "Name": "Rebecca",
  "Surname": "Mushayawaro",
  "Email": "rebeccan@gmail.com",
  "FavoriteColor": "Red",
  "Birthday": "06/04/82"
}
###
put https://mabundur341.onrender.com/contacts/6378c13da3083443dd17f463 HTTP/1.1
content-type: application/json

{
  "Name": "Sheasby",
  "Surname": "Mushayawaro",
  "Email": "sheasby@gmail.com",
  "FavoriteColor": "Yellow",
  "Birthday": "06/04/2018"
}

###
delete https://mabundur341.onrender.com/contacts/6378c13da3083443dd17f463 HTTP/1.1
